### ISSUE TITLE
[Clover] Clock App Crash

### ISSUE THREAD

**Issue by harry-cpp** [xiaomi-sdm660/android_build_bug-tracker#29]
**Device:** Mi Pad 4 LTE
**ROM Version :** Build from 6th January 2020

**Description**

Clock app crashes.

**Symptoms**

Crashes with the following exception:
```
01-13 20:28:39.575  7447  7447 D Events  : [Alarm] [Set Time] [DeskClock]
01-13 20:28:39.577  7447  7447 D Events  : [Alarm] [Expand Implied] [DeskClock]
01-13 20:28:39.728  1883  3037 E Telecom : : getUserSelectedOutgoingPhoneAccount: TSI.gUSOPA@ADY
01-13 20:28:39.728  1883  3037 E Telecom : java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10110 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
01-13 20:28:39.728  1883  3037 E Telecom : 	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
01-13 20:28:39.728  1883  3037 E Telecom : 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
01-13 20:28:39.728  1883  3037 E Telecom : 	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:800)
01-13 20:28:39.728  1883  3037 E Telecom : 	at com.android.server.telecom.TelecomServiceImpl.isDialerOrPrivileged(TelecomServiceImpl.java:1967)
01-13 20:28:39.728  1883  3037 E Telecom : 	at com.android.server.telecom.TelecomServiceImpl.access$300(TelecomServiceImpl.java:71)
01-13 20:28:39.728  1883  3037 E Telecom : 	at com.android.server.telecom.TelecomServiceImpl$1.getUserSelectedOutgoingPhoneAccount(TelecomServiceImpl.java:141)
01-13 20:28:39.728  1883  3037 E Telecom : 	at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:693)
01-13 20:28:39.728  1883  3037 E Telecom : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
01-13 20:28:39.728  1883  3037 E Telecom : 	at android.os.Binder.execTransact(Binder.java:994)
01-13 20:28:39.729  7447  7447 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
01-13 20:28:39.729  7447  7447 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
01-13 20:28:39.729  7447  7447 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
01-13 20:28:39.729  7447  7447 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
01-13 20:28:39.730  7447  7447 D Ringtone: Problem opening; delegating to remote player
01-13 20:28:39.731  1883  3037 E Telecom : : getUserSelectedOutgoingPhoneAccount: TSI.gUSOPA@ADc
01-13 20:28:39.731  1883  3037 E Telecom : java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10110 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
01-13 20:28:39.731  1883  3037 E Telecom : 	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
01-13 20:28:39.731  1883  3037 E Telecom : 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
01-13 20:28:39.731  1883  3037 E Telecom : 	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:800)
01-13 20:28:39.731  1883  3037 E Telecom : 	at com.android.server.telecom.TelecomServiceImpl.isDialerOrPrivileged(TelecomServiceImpl.java:1967)
01-13 20:28:39.731  1883  3037 E Telecom : 	at com.android.server.telecom.TelecomServiceImpl.access$300(TelecomServiceImpl.java:71)
01-13 20:28:39.731  1883  3037 E Telecom : 	at com.android.server.telecom.TelecomServiceImpl$1.getUserSelectedOutgoingPhoneAccount(TelecomServiceImpl.java:141)
01-13 20:28:39.731  1883  3037 E Telecom : 	at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:693)
01-13 20:28:39.731  1883  3037 E Telecom : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
1-13 20:28:39.733  7447  7447 D AndroidRuntime: Shutting down VM
01-13 20:28:39.734  7447  7447 E AndroidRuntime: FATAL EXCEPTION: main
01-13 20:28:39.734  7447  7447 E AndroidRuntime: Process: com.android.deskclock, PID: 7447
01-13 20:28:39.734  7447  7447 E AndroidRuntime: java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10110 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
01-13 20:28:39.734  7447  7447 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
01-13 20:28:39.734  7447  7447 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
01-13 20:28:39.734  7447  7447 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
```

**How to reproduce**

Open the Clock app, select Alarm tab and click on an existing alarm.

**Comment by rcstar6696** [comment]
No rom specified in issue and not debice related issue. Thats rom side issue

**Comment by harry-cpp** [comment]
> No rom specified in issue

Specified the roms date, everybody specified it in a random format and there was no pre-formatted template on how it should look, I assume this is better: lineage-17.1-20200106-UNOFFICIAL-clover

> Thats rom side issue

Where might I be able to report this issue?

**Comment by rcstar6696** [comment]
There is a template added by default

Lineage bug tracker
